### ISSUE TITLE
Add unit tests for `getAllElementsByPath.js`

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck-web#260]
Our JavaScript `getAllElementsByPath.js` is growing and it implements important functionality. We should add unit tests for it.

Open questions:

* How to integrate it in our CI pipeline?
* Which testing framework(s) to use for running tests, mocking, etc. (e.g. [Jest](https://jestjs.io/))?

**Comment by diba1013** [comment]
Since we use this in multiple locations now (see [chrome-plugin](https://github.com/retest/recheck-web-chrome-extension/blob/master/getAllElementsByPath.js)), it might be best to extract this into a separate project, then build it and include it somehow into those depending projects.

With a separate project, we could then use tests in JavaScript which would greatly simplify this process.
