### ISSUE TITLE
Support for cucumber

### ISSUE THREAD

**Issue by LidzeGIT** [retest/recheck-web#429]
hi, is there support for cucumber(bdd)?

**Comment by diba1013** [comment]
Sadly, we currently do not explicitly support cucumber yet. On the bright side, however, since we build upon Selenium and Java and provide various [configuration](https://docs.retest.de/recheck/usage/configuration/) endpoints, it might be possible to use cucumber now, without the explicit support.

While we currently do not practice BDD, I would be interested, how you would setup such a Selenium Test with it. Would it be possible for you to provide or link a small and basic example, that instantiates a driver and performs a assertion (or how that is called in BDD)? With that and some additional context (e.g. build tool, language), I might be able to help you with the setup and transformation of a plain Selenium Test to a recheck-web test.

**Comment by diba1013** [comment]
I tried to setup a small example [project](https://github.com/diba1013/recheck-web-cucumber-demo) with some [Stepdefs](https://github.com/diba1013/recheck-web-cucumber-demo/blob/master/src/test/java/de/diba/recheck/web/cucumber/Stepdefs.java), that does a google search as suggested by the [cucumber browser automation](https://cucumber.io/docs/guides/browser-automation/).

Please note, that I time-boxed this and it may not be the cleanest example. However, the basic example works with Maven, JUnit4 and recheck-web. Note that `google.com` is not the ideal site to test since it changes all the time. You will want to stabilize the page and ensure that it is relatively the same.

Some notes that I encountered (please refer to the [documentation](https://docs.retest.de/recheck-web/setup/maven/) to get started), since our auto detecting feature does not work:
1. You need to provide a `suiteName` via `RecheckOptions`.
2. You need to start the test with a name.

**Comment by diba1013** [comment]
I assume this is working now. If not, please feel free to reopen this issue and post additional information necessary.
