### ISSUE TITLE
NPE on latest recheck web

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#634]
- [X] this is related specifically to recheck-web and [recheck](https://github.com/retest/recheck) itself.
- [X] the [documentation](https://docs.retest.de/) does not mention a fix (e.g. wrong API usage, ...).
- [X] the bug is not related to customization (e.g. custom implementations).
- [X] there are no open or closed issues that are related to this problem.

## Describe the Bug

Null pointer exception is thrown after a recent upgrade to 1.11.1 when calling capTest().

```
NullPointerException: java.lang.NullPointerException
	at de.retest.recheck.report.SuiteReplayResult.addTest(SuiteReplayResult.java:92)
	at de.retest.recheck.RecheckImpl.capTestSilently(RecheckImpl.java:173)
	at de.retest.recheck.RecheckImpl.capTest(RecheckImpl.java:182)
	at de.retest.web.selenium.AutocheckingRecheckDriver.capTest(AutocheckingRecheckDriver.java:84)
	at com.xxxx.basetest.VisualTest.cleanupSuite(VisualTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

### How to Reproduce?

1. Configure recheck
```
recheck =
        new RecheckDriver(
            (RemoteWebDriver) getSeleniumInterface().getWebDriver(),
            RecheckOptions.builder()
                .namingStrategy(
                    new NamingStrategy() {
                      @Override
                      public String getSuiteName() {
                        return getClass().getName();
                      }

                      @Override
                      public String getTestName() {
                        return VisualTest.this.getTestName();
                      }
                    })
                .build());
```
2. Run tests.
3. Call capTest().

### Setup

- recheck-web: 1.11.1
- Selenium version: 3.141.59
- Testing framework: TestNG 7.3.0
- OS: MacOS 14
- Java version: jdk-8

**Comment by diba1013** [comment]
Thank you for reporting this. Glad to hear, you are still using recheck-web for your tests.

NPEs are usually an indicator that the state is not in a correct state. However, with the examples provided, I am unable to reproduce said state, thus all of the below are assumptions.

From the stacktrace, I gather that this has to do something with the lifecycle of recheck-web. Do you properly call all the necessary [lifecycle methods](https://docs.retest.de/recheck/introduction/usage/#lifecycle)? Things to note (please refer to the usage examples within the [documentation](https://docs.retest.de/recheck/introduction/usage/#integration-in-test-frameworks-and-plain-java)):

1. Call `recheck.startTest()` before anything else within your test method (i.e this should be the first line).
2. Call `recheck.capTest()` as the last thing within the test method (i.e. this should be the last line).
3. Call `recheck.cap()` at the end once your test method has completed (e.g. `@AfterEach`).

recheck tries its best to assume a potential lifecycle state if no methods is called. However, this might not be correct every time. Thus it is important that lifecycle methods are called in the right order. 
It is best to use one of our extensions ([JUnit4](https://github.com/retest/recheck-junit-4-extension), [JUnit5](https://github.com/retest/recheck-junit-jupiter-extension), [TestNG](https://github.com/retest/recheck-testng-extension)) to ensure the lifecycle is called properly.

Especially, recheck does have trouble assuming the lifecycle if the test is aborted with exceptions, before it could even start (e.g. driver could not be found, ...). Are there any indicators in the log that an exception happened (except the NPE), which caused the test suite to fail unexpectedly.

It would be great, if you posted more of your test class here, so that I can properly reproduce the behavior.

**Comment by javydreamercsw** [comment]
The code hasn't changed in a while but turned out that was the case. I guess something changed between versions.

Used the TestNG extension and that did the trick. Thanks!
