### ISSUE TITLE
Write all results of one test class into one result file 

### ISSUE THREAD

**Issue by kema91** [retest/recheck-web#88]
At the moment we get only one test inside a result file but we want to get all tests from a test class inside one result file.

actual:
![bildschirmfoto 2018-10-24 um 10 02 43](https://user-images.githubusercontent.com/42932182/47510411-64959580-d878-11e8-950c-a39e764d80bc.png)

expected
![bildschirmfoto 2018-10-25 um 17 06 27](https://user-images.githubusercontent.com/42932182/47510419-67908600-d878-11e8-82ce-aad3a1f1a5e5.png)

**Comment by beatngu13** [comment]
To add some more details: According to @kema91 and @oezelenes, the problem is essentially that the replay result is stored along with the instance of `RecheckImpl`. Since we create a new object for each test (`@Before`/`@BeforeEach`/…), this gets overwritten.

However, I think we want to use that lifecycle because a) to be compliant with how Selenium tests are usually written and b) to not share an instance among tests. What we need is a single instance ([not necessarily a singleton](https://softwareengineering.stackexchange.com/questions/40373/so-singletons-are-bad-then-what)) that stores that the test results and that can be accessed from each `RecheckImpl` instance.

Suggestions?
